max_iterations: 20
use_speech_recognition: false
characters:
  - id: "avatar1"
    name: "ずんだもん"
    prompt_file: "characters/character1.xml"
  - id: "avatar2"
    name: "四国めたん"
    prompt_file: "characters/character2.xml"
